name: countries_app
description: "A Flutter Bloc study project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  equatable: ^2.0.7
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.1.0
  auto_route: ^10.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
